package uet.ndh.ddsl.codegen.poet.translator;

import com.palantir.javapoet.*;
import uet.ndh.ddsl.ast.behavior.BehaviorDecl;
import uet.ndh.ddsl.ast.model.event.EventHandlerDecl;
import uet.ndh.ddsl.ast.model.event.EventHandlerContainerDecl;
import uet.ndh.ddsl.codegen.CodeArtifact;
import uet.ndh.ddsl.codegen.poet.TypeMapper;

import javax.lang.model.element.Modifier;
import java.util.ArrayList;
import java.util.List;

/**
 * Translates EventHandlerDecl AST nodes to hexagonal architecture event handlers and consumers.
 * 
 * Generates three types of artifacts:
 * 1. Handler classes in application/ package (implement EventHandler and EventSubscriber)
 * 2. Consumer classes in infrastructure/ package (abstract adapter for messaging)
 * 3. BaseEventPublisher abstract class in infrastructure/ package (template for event publishing)
 */
public class EventHandlerTranslator {
    
    private final TypeMapper typeMapper;
    
    public EventHandlerTranslator(TypeMapper typeMapper) {
        this.typeMapper = typeMapper;
    }
    
    /**
     * Translate an EventHandlerContainerDecl to a list of CodeArtifacts.
     * Generates handlers, consumers, and BaseEventPublisher.
     */
    public List<CodeArtifact> translate(EventHandlerContainerDecl container) {
        List<CodeArtifact> artifacts = new ArrayList<>();
        String applicationPackage = typeMapper.getApplicationPackage();
        String infrastructurePackage = typeMapper.getInfrastructurePackage();
        
        // Generate BaseEventPublisher once per container
        JavaFile basePublisherFile = generateBaseEventPublisher(infrastructurePackage);
        artifacts.add(new CodeArtifact(
            "BaseEventPublisher",
            infrastructurePackage,
            basePublisherFile.toString(),
            CodeArtifact.ArtifactType.CLASS
        ));
        
        for (EventHandlerDecl handler : container.handlers()) {
            // Generate handler in application/ package
            JavaFile handlerFile = translateHandler(handler, applicationPackage);
            artifacts.add(new CodeArtifact(
                handler.name(),
                applicationPackage,
                handlerFile.toString(),
                CodeArtifact.ArtifactType.CLASS
            ));
            
            // Generate consumer in infrastructure/ package
            JavaFile consumerFile = translateConsumer(handler, infrastructurePackage);
            artifacts.add(new CodeArtifact(
                handler.name() + "Consumer",
                infrastructurePackage,
                consumerFile.toString(),
                CodeArtifact.ArtifactType.CLASS
            ));
        }
        
        return artifacts;
    }
    
    /**
     * Generate BaseEventPublisher abstract class in infrastructure package.
     */
    private JavaFile generateBaseEventPublisher(String packageName) {
        ClassName eventPublisherInterface = typeMapper.getEventPublisherInterface();
        ClassName domainEventInterface = typeMapper.getDomainEventInterface();
        
        MethodSpec doPublishMethod = MethodSpec.methodBuilder("doPublish")
            .addModifiers(Modifier.PROTECTED, Modifier.ABSTRACT)
            .addParameter(domainEventInterface, "event")
            .build();
        
        MethodSpec publishMethod = MethodSpec.methodBuilder("publish")
            .addModifiers(Modifier.PUBLIC)
            .addAnnotation(Override.class)
            .addParameter(domainEventInterface, "event")
            .beginControlFlow("if (event == null)")
            .addStatement("throw new IllegalArgumentException(\"Event cannot be null\")")
            .endControlFlow()
            .addStatement("doPublish(event)")
            .build();
        
        MethodSpec publishAllMethod = MethodSpec.methodBuilder("publishAll")
            .addModifiers(Modifier.PUBLIC)
            .addAnnotation(Override.class)
            .addParameter(ParameterizedTypeName.get(ClassName.get(List.class), 
                WildcardTypeName.subtypeOf(domainEventInterface)), "events")
            .beginControlFlow("for ($T event : events)", domainEventInterface)
            .addStatement("publish(event)")
            .endControlFlow()
            .build();
        
        TypeSpec basePublisherClass = TypeSpec.classBuilder("BaseEventPublisher")
            .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
            .addSuperinterface(eventPublisherInterface)
            .addMethod(doPublishMethod)
            .addMethod(publishMethod)
            .addMethod(publishAllMethod)
            .build();
        
        return JavaFile.builder(packageName, basePublisherClass)
            .addFileComment("Generated by DDSL - Base Event Publisher")
            .build();
    }
    
    /**
     * Translate a single EventHandlerDecl to a handler JavaFile in application/ package.
     */
    private JavaFile translateHandler(EventHandlerDecl handler, String packageName) {
        String className = handler.name();
        ClassName eventHandlerInterface = typeMapper.getEventHandlerInterface();
        ClassName eventSubscriberInterface = typeMapper.getEventSubscriberInterface();
        ClassName targetEventClass = typeMapper.resolveDomainClassName(handler.targetEventName());
        ClassName domainEventClass = typeMapper.getDomainEventInterface();
        
        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
            .addModifiers(Modifier.PUBLIC)
            .addSuperinterface(eventHandlerInterface)
            .addSuperinterface(eventSubscriberInterface)
            .addJavadoc("Event handler for $L.\n", handler.targetEventName());
        
        // Add subscribedTo() method
        MethodSpec subscribedToMethod = MethodSpec.methodBuilder("subscribedTo")
            .addModifiers(Modifier.PUBLIC)
            .addAnnotation(Override.class)
            .returns(ParameterizedTypeName.get(ClassName.get(Class.class), 
                WildcardTypeName.subtypeOf(domainEventClass)))
            .addStatement("return $T.class", targetEventClass)
            .build();
        classBuilder.addMethod(subscribedToMethod);
        
        // Add onEvent(DomainEvent) method
        MethodSpec onEventMethod = MethodSpec.methodBuilder("onEvent")
            .addModifiers(Modifier.PUBLIC)
            .addAnnotation(Override.class)
            .addParameter(domainEventClass, "event")
            .addStatement("handle(event)")
            .build();
        classBuilder.addMethod(onEventMethod);
        
        // Add handle(DomainEvent) method with cast
        MethodSpec handleDomainEventMethod = MethodSpec.methodBuilder("handle")
            .addModifiers(Modifier.PUBLIC)
            .addAnnotation(Override.class)
            .addParameter(domainEventClass, "event")
            .addStatement("handle(($T) event)", targetEventClass)
            .build();
        classBuilder.addMethod(handleDomainEventMethod);
        
        // Add typed handle(TargetEvent) method
        MethodSpec handleTypedMethod = MethodSpec.methodBuilder("handle")
            .addModifiers(Modifier.PUBLIC)
            .addParameter(targetEventClass, "event")
            .addStatement("// TODO: Implement handler logic for $L", handler.targetEventName())
            .build();
        classBuilder.addMethod(handleTypedMethod);
        
        return JavaFile.builder(packageName, classBuilder.build())
            .addFileComment("Generated by DDSL - Event Handler")
            .build();
    }
    
    /**
     * Translate a single EventHandlerDecl to a consumer JavaFile in infrastructure/ package.
     */
    private JavaFile translateConsumer(EventHandlerDecl handler, String packageName) {
        String consumerClassName = handler.name() + "Consumer";
        ClassName handlerClassName = ClassName.get(typeMapper.getApplicationPackage(), handler.name());
        ClassName domainEventClass = typeMapper.getDomainEventInterface();
        
        // Add handler field
        FieldSpec handlerField = FieldSpec.builder(handlerClassName, "handler", 
            Modifier.PRIVATE, Modifier.FINAL).build();
        
        // Add constructor
        MethodSpec constructor = MethodSpec.constructorBuilder()
            .addModifiers(Modifier.PUBLIC)
            .addParameter(handlerClassName, "handler")
            .addStatement("this.handler = handler")
            .build();
        
        // Add abstract deserialize method
        MethodSpec deserializeMethod = MethodSpec.methodBuilder("deserialize")
            .addModifiers(Modifier.PROTECTED, Modifier.ABSTRACT)
            .returns(domainEventClass)
            .addParameter(String.class, "message")
            .build();
        
        // Add onMessage method
        MethodSpec onMessageMethod = MethodSpec.methodBuilder("onMessage")
            .addModifiers(Modifier.PUBLIC)
            .addParameter(String.class, "message")
            .addStatement("$T event = deserialize(message)", domainEventClass)
            .addStatement("handler.handle(event)")
            .build();
        
        TypeSpec consumerClass = TypeSpec.classBuilder(consumerClassName)
            .addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
            .addField(handlerField)
            .addMethod(constructor)
            .addMethod(deserializeMethod)
            .addMethod(onMessageMethod)
            .build();
        
        return JavaFile.builder(packageName, consumerClass)
            .addFileComment("Generated by DDSL - Event Consumer")
            .build();
    }
}
