package uet.ndh.ddsl.codegen.poet.translator;

import com.palantir.javapoet.*;
import uet.ndh.ddsl.ast.behavior.BehaviorDecl;
import uet.ndh.ddsl.ast.model.event.EventHandlerDecl;
import uet.ndh.ddsl.ast.model.event.EventHandlerContainerDecl;
import uet.ndh.ddsl.codegen.CodeArtifact;
import uet.ndh.ddsl.codegen.poet.TypeMapper;

import javax.lang.model.element.Modifier;
import java.util.ArrayList;
import java.util.List;

/**
 * Translates EventHandlerDecl AST nodes to plain Java event handler classes.
 */
public class EventHandlerTranslator {
    
    private final TypeMapper typeMapper;
    private final ExpressionTranslator expressionTranslator;
    
    public EventHandlerTranslator(TypeMapper typeMapper) {
        this.typeMapper = typeMapper;
        this.expressionTranslator = new ExpressionTranslator(typeMapper);
    }
    
    /**
     * Translate an EventHandlerContainerDecl to a list of CodeArtifacts.
     */
    public List<CodeArtifact> translate(EventHandlerContainerDecl container) {
        List<CodeArtifact> artifacts = new ArrayList<>();
        String listenerPackage = typeMapper.getListenerPackage();
        
        for (EventHandlerDecl handler : container.handlers()) {
            JavaFile handlerFile = translateHandler(handler, listenerPackage);
            artifacts.add(new CodeArtifact(
                handler.name(),
                listenerPackage,
                handlerFile.toString(),
                CodeArtifact.ArtifactType.CLASS
            ));
        }
        
        return artifacts;
    }
    
    /**
     * Translate a single EventHandlerDecl to a JavaFile.
     */
    private JavaFile translateHandler(EventHandlerDecl handler, String packageName) {
        String className = handler.name();

        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(className)
            .addModifiers(Modifier.PUBLIC)
            .addJavadoc("Event handler for $L.\n", handler.targetEventName());

        for (int i = 0; i < handler.behaviors().size(); i++) {
            BehaviorDecl behavior = handler.behaviors().get(i);
            MethodSpec handlerMethod = buildHandlerMethod(behavior, handler.targetEventName(), i);
            classBuilder.addMethod(handlerMethod);
        }

        // If no behaviors, add a default handle method
        if (handler.behaviors().isEmpty()) {
            MethodSpec defaultMethod = buildDefaultHandlerMethod(handler.targetEventName());
            classBuilder.addMethod(defaultMethod);
        }

        return JavaFile.builder(packageName, classBuilder.build())
            .addFileComment("Generated by DDSL - Event Handler")
            .build();
    }
    
    private MethodSpec buildHandlerMethod(BehaviorDecl behavior, String eventName, int index) {
        String methodName = "handle";

        ClassName eventClass = typeMapper.resolveDomainClassName(eventName);

        return MethodSpec.methodBuilder(methodName)
            .addModifiers(Modifier.PUBLIC)
            .addParameter(eventClass, "event")
            .addStatement("// TODO: Implement handler logic for $L", behavior.getName())
            .build();
    }
    
    private MethodSpec buildDefaultHandlerMethod(String eventName) {
        ClassName eventClass = typeMapper.resolveDomainClassName(eventName);

        return MethodSpec.methodBuilder("handle")
            .addModifiers(Modifier.PUBLIC)
            .addParameter(eventClass, "event")
            .addStatement("// TODO: Implement handler logic for $L", eventName)
            .build();
    }
}
