package uet.ndh.ddsl.ast.model.entity;

import uet.ndh.ddsl.ast.SourceSpan;
import uet.ndh.ddsl.ast.common.TypeRef;

/**
 * Represents an identity field in an entity.
 * Pure data record.
 */
public record IdentityFieldDecl(
    SourceSpan span,
    String name,
    TypeRef type,
    IdentityType identityType,
    IdGenerationStrategy strategy
) {
    
    /**
     * Type of identity value.
     */
    public enum IdentityType {
        UUID,
        LONG,
        STRING,
        COMPOSITE,
        CUSTOM
    }
    
    /**
     * Strategy for generating identity values.
     */
    public enum IdGenerationStrategy {
        AUTO,               // Auto-generated by the system
        CLIENT_GENERATED,   // Client provides the ID
        SERVER_GENERATED,   // Server generates the ID (auto-increment, sequence)
        UUID,               // UUID generation
        CUSTOM              // Custom generation logic
    }
}
